# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu-ui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 478)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.choosePathLayout = QtWidgets.QHBoxLayout()
        self.choosePathLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.choosePathLayout.setObjectName("choosePathLayout")
        self.pathButton = QtWidgets.QPushButton(self.centralwidget)
        self.pathButton.setMinimumSize(QtCore.QSize(130, 25))
        self.pathButton.setMaximumSize(QtCore.QSize(130, 25))
        self.pathButton.setObjectName("pathButton")
        self.choosePathLayout.addWidget(self.pathButton)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.choosePathLayout.addWidget(self.lineEdit)
        self.chooseFileType = QtWidgets.QComboBox(self.centralwidget)
        self.chooseFileType.setMinimumSize(QtCore.QSize(80, 25))
        self.chooseFileType.setMaximumSize(QtCore.QSize(80, 25))
        self.chooseFileType.setObjectName("chooseFileType")
        self.choosePathLayout.addWidget(self.chooseFileType)
        self.choosePathLayout.setStretch(0, 1)
        self.mainLayout.addLayout(self.choosePathLayout)
        self.dataLayout = QtWidgets.QHBoxLayout()
        self.dataLayout.setObjectName("dataLayout")
        self.plotData = QtWidgets.QPushButton(self.centralwidget)
        self.plotData.setObjectName("plotData")
        self.dataLayout.addWidget(self.plotData)
        self.mainLayout.addLayout(self.dataLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.psdTab = QtWidgets.QWidget()
        self.psdTab.setObjectName("psdTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.psdTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.methodLabel = QtWidgets.QLabel(self.psdTab)
        self.methodLabel.setMinimumSize(QtCore.QSize(130, 25))
        self.methodLabel.setMaximumSize(QtCore.QSize(130, 25))
        self.methodLabel.setObjectName("methodLabel")
        self.horizontalLayout.addWidget(self.methodLabel)
        self.psdMethod = QtWidgets.QComboBox(self.psdTab)
        self.psdMethod.setMinimumSize(QtCore.QSize(300, 25))
        self.psdMethod.setMaximumSize(QtCore.QSize(16777215, 25))
        self.psdMethod.setAccessibleName("")
        self.psdMethod.setCurrentText("")
        self.psdMethod.setObjectName("psdMethod")
        self.horizontalLayout.addWidget(self.psdMethod)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.parametersLabel = QtWidgets.QLabel(self.psdTab)
        self.parametersLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.parametersLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.parametersLabel.setObjectName("parametersLabel")
        self.verticalLayout_3.addWidget(self.parametersLabel)
        self.textEdit = QtWidgets.QTextEdit(self.psdTab)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.psdButton = QtWidgets.QPushButton(self.psdTab)
        self.psdButton.setObjectName("psdButton")
        self.verticalLayout_3.addWidget(self.psdButton)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.tabWidget.addTab(self.psdTab, "")
        self.tfrTab = QtWidgets.QWidget()
        self.tfrTab.setObjectName("tfrTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tfrTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.methodLabel_3 = QtWidgets.QLabel(self.tfrTab)
        self.methodLabel_3.setMinimumSize(QtCore.QSize(130, 25))
        self.methodLabel_3.setMaximumSize(QtCore.QSize(130, 25))
        self.methodLabel_3.setObjectName("methodLabel_3")
        self.horizontalLayout_3.addWidget(self.methodLabel_3)
        self.psdMethodParameters_3 = QtWidgets.QComboBox(self.tfrTab)
        self.psdMethodParameters_3.setMinimumSize(QtCore.QSize(300, 25))
        self.psdMethodParameters_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.psdMethodParameters_3.setAccessibleName("")
        self.psdMethodParameters_3.setCurrentText("")
        self.psdMethodParameters_3.setObjectName("psdMethodParameters_3")
        self.horizontalLayout_3.addWidget(self.psdMethodParameters_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label = QtWidgets.QLabel(self.tfrTab)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.tfrButton = QtWidgets.QPushButton(self.tfrTab)
        self.tfrButton.setObjectName("tfrButton")
        self.verticalLayout.addWidget(self.tfrButton)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 3)
        self.tabWidget.addTab(self.tfrTab, "")
        self.mainLayout.addWidget(self.tabWidget)
        self.mainLayout.setStretch(0, 1)
        self.mainLayout.setStretch(1, 1)
        self.mainLayout.setStretch(2, 100)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pathButton.setText(_translate("MainWindow", "Choose Path"))
        self.plotData.setText(_translate("MainWindow", "Visualize Data"))
        self.methodLabel.setText(_translate("MainWindow", "Method"))
        self.parametersLabel.setText(_translate("MainWindow", "Parameters"))
        self.psdButton.setText(_translate("MainWindow", "Visualize PSD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.psdTab), _translate("MainWindow", "PSD "))
        self.methodLabel_3.setText(_translate("MainWindow", "Method"))
        self.label.setText(_translate("MainWindow", "Parameters"))
        self.tfrButton.setText(_translate("MainWindow", "Visualize TFR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tfrTab), _translate("MainWindow", "TFR"))
