# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu-ui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuWindow(object):
    def setupUi(self, MenuWindow):
        MenuWindow.setObjectName("MenuWindow")
        MenuWindow.resize(572, 402)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Time-Frequency-Module/media/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MenuWindow.setWindowIcon(icon)
        MenuWindow.setAutoFillBackground(False)
        MenuWindow.setDocumentMode(False)
        MenuWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MenuWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MenuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(5, 9, 5, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.upper = QtWidgets.QWidget(self.centralwidget)
        self.upper.setObjectName("upper")
        self.UpperLayout = QtWidgets.QVBoxLayout(self.upper)
        self.UpperLayout.setContentsMargins(0, 0, 0, 0)
        self.UpperLayout.setSpacing(0)
        self.UpperLayout.setObjectName("UpperLayout")
        self.choosePathLayout = QtWidgets.QHBoxLayout()
        self.choosePathLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.choosePathLayout.setSpacing(0)
        self.choosePathLayout.setObjectName("choosePathLayout")
        self.pathButton = QtWidgets.QPushButton(self.upper)
        self.pathButton.setMinimumSize(QtCore.QSize(130, 25))
        self.pathButton.setMaximumSize(QtCore.QSize(130, 25))
        self.pathButton.setFlat(False)
        self.pathButton.setObjectName("pathButton")
        self.choosePathLayout.addWidget(self.pathButton)
        self.lineEdit = QtWidgets.QLineEdit(self.upper)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit.setFrame(True)
        self.lineEdit.setObjectName("lineEdit")
        self.choosePathLayout.addWidget(self.lineEdit)
        self.chooseFileType = QtWidgets.QComboBox(self.upper)
        self.chooseFileType.setMinimumSize(QtCore.QSize(130, 25))
        self.chooseFileType.setMaximumSize(QtCore.QSize(130, 25))
        self.chooseFileType.setFrame(False)
        self.chooseFileType.setObjectName("chooseFileType")
        self.choosePathLayout.addWidget(self.chooseFileType)
        self.UpperLayout.addLayout(self.choosePathLayout)
        self.line_3 = QtWidgets.QFrame(self.upper)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.UpperLayout.addWidget(self.line_3)
        self.dataLayout = QtWidgets.QHBoxLayout()
        self.dataLayout.setSpacing(0)
        self.dataLayout.setObjectName("dataLayout")
        self.displayDataButton = QtWidgets.QPushButton(self.upper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(130)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.displayDataButton.sizePolicy().hasHeightForWidth())
        self.displayDataButton.setSizePolicy(sizePolicy)
        self.displayDataButton.setMinimumSize(QtCore.QSize(130, 25))
        self.displayDataButton.setMaximumSize(QtCore.QSize(130, 25))
        self.displayDataButton.setFlat(False)
        self.displayDataButton.setObjectName("displayDataButton")
        self.dataLayout.addWidget(self.displayDataButton)
        self.plotData = QtWidgets.QPushButton(self.upper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(130)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.plotData.sizePolicy().hasHeightForWidth())
        self.plotData.setSizePolicy(sizePolicy)
        self.plotData.setMinimumSize(QtCore.QSize(130, 25))
        self.plotData.setMaximumSize(QtCore.QSize(5614651, 25))
        self.plotData.setFlat(False)
        self.plotData.setObjectName("plotData")
        self.dataLayout.addWidget(self.plotData)
        self.epochingButton = QtWidgets.QPushButton(self.upper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.epochingButton.sizePolicy().hasHeightForWidth())
        self.epochingButton.setSizePolicy(sizePolicy)
        self.epochingButton.setMinimumSize(QtCore.QSize(130, 25))
        self.epochingButton.setMaximumSize(QtCore.QSize(130, 25))
        self.epochingButton.setFlat(False)
        self.epochingButton.setObjectName("epochingButton")
        self.dataLayout.addWidget(self.epochingButton)
        self.UpperLayout.addLayout(self.dataLayout)
        self.line_2 = QtWidgets.QFrame(self.upper)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.UpperLayout.addWidget(self.line_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.upper)
        self.label_4.setMinimumSize(QtCore.QSize(130, 25))
        self.label_4.setMaximumSize(QtCore.QSize(130, 25))
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setLineWidth(2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.xyzPath = QtWidgets.QLineEdit(self.upper)
        self.xyzPath.setFrame(True)
        self.xyzPath.setObjectName("xyzPath")
        self.horizontalLayout_6.addWidget(self.xyzPath)
        self.electrodeMontage = QtWidgets.QComboBox(self.upper)
        self.electrodeMontage.setMinimumSize(QtCore.QSize(130, 25))
        self.electrodeMontage.setMaximumSize(QtCore.QSize(130, 25))
        self.electrodeMontage.setFrame(False)
        self.electrodeMontage.setObjectName("electrodeMontage")
        self.horizontalLayout_6.addWidget(self.electrodeMontage)
        self.UpperLayout.addLayout(self.horizontalLayout_6)
        self.line = QtWidgets.QFrame(self.upper)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.UpperLayout.addWidget(self.line)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.upper)
        self.label_3.setMinimumSize(QtCore.QSize(130, 25))
        self.label_3.setMaximumSize(QtCore.QSize(130, 25))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.displayChannel = QtWidgets.QLineEdit(self.upper)
        self.displayChannel.setObjectName("displayChannel")
        self.horizontalLayout_7.addWidget(self.displayChannel)
        self.pushButton = QtWidgets.QPushButton(self.upper)
        self.pushButton.setMinimumSize(QtCore.QSize(130, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(130, 25))
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.UpperLayout.addLayout(self.horizontalLayout_7)
        self.mainLayout.addWidget(self.upper)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.psdTab = QtWidgets.QWidget()
        self.psdTab.setObjectName("psdTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.psdTab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalWidget = QtWidgets.QWidget(self.psdTab)
        self.verticalWidget.setObjectName("verticalWidget")
        self.tabLayout1 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.tabLayout1.setContentsMargins(0, 0, 0, 0)
        self.tabLayout1.setSpacing(0)
        self.tabLayout1.setObjectName("tabLayout1")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.methodLabel = QtWidgets.QLabel(self.verticalWidget)
        self.methodLabel.setMinimumSize(QtCore.QSize(100, 25))
        self.methodLabel.setMaximumSize(QtCore.QSize(100, 25))
        self.methodLabel.setObjectName("methodLabel")
        self.horizontalLayout.addWidget(self.methodLabel)
        self.psdMethod = QtWidgets.QComboBox(self.verticalWidget)
        self.psdMethod.setMinimumSize(QtCore.QSize(150, 25))
        self.psdMethod.setMaximumSize(QtCore.QSize(16777215, 25))
        self.psdMethod.setAccessibleName("")
        self.psdMethod.setCurrentText("")
        self.psdMethod.setObjectName("psdMethod")
        self.horizontalLayout.addWidget(self.psdMethod)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.tabLayout1.addLayout(self.horizontalLayout)
        self.line_4 = QtWidgets.QFrame(self.verticalWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.tabLayout1.addWidget(self.line_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalWidget)
        self.label_2.setMinimumSize(QtCore.QSize(100, 25))
        self.label_2.setMaximumSize(QtCore.QSize(100, 25))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.psdParametersLine = QtWidgets.QLineEdit(self.verticalWidget)
        self.psdParametersLine.setMinimumSize(QtCore.QSize(100, 25))
        self.psdParametersLine.setMaximumSize(QtCore.QSize(16777215, 25))
        self.psdParametersLine.setFrame(False)
        self.psdParametersLine.setObjectName("psdParametersLine")
        self.horizontalLayout_2.addWidget(self.psdParametersLine)
        self.psdParametersButton = QtWidgets.QPushButton(self.verticalWidget)
        self.psdParametersButton.setMinimumSize(QtCore.QSize(130, 25))
        self.psdParametersButton.setMaximumSize(QtCore.QSize(130, 25))
        self.psdParametersButton.setObjectName("psdParametersButton")
        self.horizontalLayout_2.addWidget(self.psdParametersButton)
        self.tabLayout1.addLayout(self.horizontalLayout_2)
        self.line_7 = QtWidgets.QFrame(self.verticalWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.tabLayout1.addWidget(self.line_7)
        self.psdParametersText = QtWidgets.QTextEdit(self.verticalWidget)
        self.psdParametersText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.psdParametersText.setFrameShadow(QtWidgets.QFrame.Plain)
        self.psdParametersText.setLineWidth(1)
        self.psdParametersText.setObjectName("psdParametersText")
        self.tabLayout1.addWidget(self.psdParametersText)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.psdButton = QtWidgets.QPushButton(self.verticalWidget)
        self.psdButton.setObjectName("psdButton")
        self.horizontalLayout_5.addWidget(self.psdButton)
        self.savePsdButton = QtWidgets.QPushButton(self.verticalWidget)
        self.savePsdButton.setObjectName("savePsdButton")
        self.horizontalLayout_5.addWidget(self.savePsdButton)
        self.tabLayout1.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.verticalWidget)
        self.tabWidget.addTab(self.psdTab, "")
        self.tfrTab = QtWidgets.QWidget()
        self.tfrTab.setObjectName("tfrTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tfrTab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.methodLabel_3 = QtWidgets.QLabel(self.tfrTab)
        self.methodLabel_3.setMinimumSize(QtCore.QSize(100, 25))
        self.methodLabel_3.setMaximumSize(QtCore.QSize(100, 25))
        self.methodLabel_3.setObjectName("methodLabel_3")
        self.horizontalLayout_3.addWidget(self.methodLabel_3)
        self.tfrMethodBox = QtWidgets.QComboBox(self.tfrTab)
        self.tfrMethodBox.setMinimumSize(QtCore.QSize(150, 25))
        self.tfrMethodBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.tfrMethodBox.setAccessibleName("")
        self.tfrMethodBox.setCurrentText("")
        self.tfrMethodBox.setObjectName("tfrMethodBox")
        self.horizontalLayout_3.addWidget(self.tfrMethodBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_5 = QtWidgets.QFrame(self.tfrTab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.tfrTab)
        self.label.setMinimumSize(QtCore.QSize(100, 25))
        self.label.setMaximumSize(QtCore.QSize(100, 25))
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.tfrParametersLine = QtWidgets.QLineEdit(self.tfrTab)
        self.tfrParametersLine.setMinimumSize(QtCore.QSize(300, 25))
        self.tfrParametersLine.setMaximumSize(QtCore.QSize(16777215, 25))
        self.tfrParametersLine.setFrame(True)
        self.tfrParametersLine.setObjectName("tfrParametersLine")
        self.horizontalLayout_4.addWidget(self.tfrParametersLine)
        self.tfrParametersButton = QtWidgets.QPushButton(self.tfrTab)
        self.tfrParametersButton.setMinimumSize(QtCore.QSize(130, 25))
        self.tfrParametersButton.setMaximumSize(QtCore.QSize(130, 25))
        self.tfrParametersButton.setObjectName("tfrParametersButton")
        self.horizontalLayout_4.addWidget(self.tfrParametersButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_6 = QtWidgets.QFrame(self.tfrTab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.tfrParametersText = QtWidgets.QTextEdit(self.tfrTab)
        self.tfrParametersText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tfrParametersText.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tfrParametersText.setObjectName("tfrParametersText")
        self.verticalLayout.addWidget(self.tfrParametersText)
        self.tfrButton = QtWidgets.QPushButton(self.tfrTab)
        self.tfrButton.setObjectName("tfrButton")
        self.verticalLayout.addWidget(self.tfrButton)
        self.tabWidget.addTab(self.tfrTab, "")
        self.mainLayout.addWidget(self.tabWidget)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 25))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_5.setObjectName("label_5")
        self.mainLayout.addWidget(self.label_5)
        self.mainLayout.setStretch(1, 1)
        MenuWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MenuWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 572, 22))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MenuWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MenuWindow)
        self.statusbar.setObjectName("statusbar")
        MenuWindow.setStatusBar(self.statusbar)
        self.actionHow_To = QtWidgets.QAction(MenuWindow)
        self.actionHow_To.setObjectName("actionHow_To")
        self.actionAbout_Parameters = QtWidgets.QAction(MenuWindow)
        self.actionAbout_Parameters.setObjectName("actionAbout_Parameters")
        self.menuHelp.addAction(self.actionHow_To)
        self.menuHelp.addAction(self.actionAbout_Parameters)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MenuWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MenuWindow)

    def retranslateUi(self, MenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuWindow.setWindowTitle(_translate("MenuWindow", "PSD Frequency Visualizer"))
        self.pathButton.setText(_translate("MenuWindow", "Choose Path"))
        self.displayDataButton.setText(_translate("MenuWindow", "Data Informations"))
        self.plotData.setText(_translate("MenuWindow", "Visualize Data"))
        self.epochingButton.setText(_translate("MenuWindow", "Cut into Epochs"))
        self.label_4.setText(_translate("MenuWindow", "Electrode Labeling"))
        self.label_3.setText(_translate("MenuWindow", "Channels Picking"))
        self.pushButton.setText(_translate("MenuWindow", "Select Channels"))
        self.methodLabel.setText(_translate("MenuWindow", "Method"))
        self.label_2.setText(_translate("MenuWindow", "Parameters"))
        self.psdParametersButton.setText(_translate("MenuWindow", "Import "))
        self.psdButton.setText(_translate("MenuWindow", "Visualize PSD"))
        self.savePsdButton.setText(_translate("MenuWindow", "Save PSD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.psdTab), _translate("MenuWindow", "PSD "))
        self.methodLabel_3.setText(_translate("MenuWindow", "Method"))
        self.label.setText(_translate("MenuWindow", "Parameters"))
        self.tfrParametersButton.setText(_translate("MenuWindow", "Import"))
        self.tfrButton.setText(_translate("MenuWindow", "Visualize TFR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tfrTab), _translate("MenuWindow", "TFR"))
        self.label_5.setText(_translate("MenuWindow", "-- Fondation Campus Biotech Geneva --"))
        self.menuHelp.setTitle(_translate("MenuWindow", "Help"))
        self.actionHow_To.setText(_translate("MenuWindow", "How To Use ? "))
        self.actionAbout_Parameters.setText(_translate("MenuWindow", "About Parameters"))
